### ISSUE TITLE
xcom-ufo.yaml

### ISSUE THREAD

**Issue by marcus682** [a-detiste/game-data-packager#3]
Hello,

in this file, the install dir should be usr/share/openxcom/data/UFO not usr/share/openxcom/UFO to be compatible with openxcom 1.02 (lastest version)

**Comment by a-detiste** [comment]
Hi,
Last relase I see is 1.00 from Jun 13 2014.
https://github.com/SupSuper/OpenXcom/releases

Were did you found this 1.02 version ?

**Comment by smcv** [comment]
See, this? This is why we should put game data in a location that depends only on the game, and not on the engine. :-)

**Comment by a-detiste** [comment]
This layout is based on the "nightlies" build.

Problem here is that OpenXCom v1 used one layout and v2 will be using another one, but v2 is not yet released. Maybe I could package v1 rightaway with a patch to make it already use v2 directory layout as an interim solution.

Or maybe some symlinks would do the trick.

@smcv 
I know :sweat: . I did it right with OpenTyrian where I handled both halves.

**Comment by marcus682** [comment]
La version c'était plutôt 1.0-2 enfaite, j'avais lu trop vite. Oui je me suis débrouillé avec des liens, c'était surtout pour qie

**Comment by marcus682** [comment]
Surtout pour que ça marche tout de suite sans bidouillages.

**Comment by a-detiste** [comment]
I see now what you're talking about:

https://launchpad.net/~knapsu/+archive/ubuntu/openxcom/+build/10629499
openxcom_1.0-2~xenial2_amd64.deb (1.9 MiB)

----

https://launchpad.net/~knapsu/+archive/ubuntu/openxcom
"Official Ubuntu packages for OpenXcom strategy game."

**Comment by a-detiste** [comment]
Basicaly all current v1.0 installs will break when 2.0 is released:
http://ufopaedia.org/index.php/Installing_(OpenXcom)

Il y aura donc encore des bidouillages.

Le mieux est de demander un 1.0-3 avec un patch qui
utiliser le path de v2.0
